export interface DeepgramVoiceOption {
  id: string;
  label: string;
}

export const DEEPGRAM_VOICES: DeepgramVoiceOption[] = [
  { id: 'amalthea', label: 'Amalthea – cheerful' },
  { id: 'andromeda', label: 'Andromeda – casual' },
  { id: 'apollo', label: 'Apollo – confident' },
  { id: 'arcas', label: 'Arcas – smooth' },
  { id: 'aries', label: 'Aries – warm' },
  { id: 'asteria', label: 'Asteria – energetic' },
  { id: 'athena', label: 'Athena – professional' },
  { id: 'atlas', label: 'Atlas – friendly' },
  { id: 'aurora', label: 'Aurora – expressive' },
  { id: 'callista', label: 'Callista – professional' },
  { id: 'cora', label: 'Cora – caring' },
  { id: 'cordelia', label: 'Cordelia – warm' },
  { id: 'delia', label: 'Delia – cheerful' },
  { id: 'draco', label: 'Draco – trustworthy' },
  { id: 'electra', label: 'Electra – knowledgeable' },
  { id: 'harmonia', label: 'Harmonia – calm' },
  { id: 'helena', label: 'Helena – friendly' },
  { id: 'hera', label: 'Hera – professional' },
  { id: 'hermes', label: 'Hermes – engaging' },
  { id: 'hyperion', label: 'Hyperion – empathetic' },
  { id: 'iris', label: 'Iris – cheerful' },
  { id: 'janus', label: 'Janus – trustworthy' },
  { id: 'juno', label: 'Juno – melodic' },
  { id: 'jupiter', label: 'Jupiter – knowledgeable' },
  { id: 'luna', label: 'Luna – friendly' },
  { id: 'mars', label: 'Mars – smooth' },
  { id: 'minerva', label: 'Minerva – friendly' },
  { id: 'neptune', label: 'Neptune – polite' },
  { id: 'odysseus', label: 'Odysseus – calm' },
  { id: 'ophelia', label: 'Ophelia – enthusiastic' },
  { id: 'orion', label: 'Orion – calm' },
  { id: 'orpheus', label: 'Orpheus – confident' },
  { id: 'pandora', label: 'Pandora – melodic' },
  { id: 'phoebe', label: 'Phoebe – energetic' },
  { id: 'pluto', label: 'Pluto – empathetic' },
  { id: 'saturn', label: 'Saturn – confident' },
  { id: 'selene', label: 'Selene – energetic' },
  { id: 'thalia', label: 'Thalia – enthusiastic' },
  { id: 'theia', label: 'Theia – polite' },
  { id: 'vesta', label: 'Vesta – patient' },
  { id: 'zeus', label: 'Zeus – deep' },
];
