export interface DeepgramVoiceOption {
  id: string;
  label: string;
  gender: 'Male' | 'Female';
}

export const DEEPGRAM_VOICES: DeepgramVoiceOption[] = [
  { id: 'amalthea', label: 'Amalthea – cheerful', gender: 'Female' },
  { id: 'andromeda', label: 'Andromeda – casual', gender: 'Female' },
  { id: 'apollo', label: 'Apollo – confident', gender: 'Male' },
  { id: 'arcas', label: 'Arcas – smooth', gender: 'Male' },
  { id: 'aries', label: 'Aries – warm', gender: 'Male' },
  { id: 'asteria', label: 'Asteria – energetic', gender: 'Female' },
  { id: 'athena', label: 'Athena – professional', gender: 'Female' },
  { id: 'atlas', label: 'Atlas – friendly', gender: 'Male' },
  { id: 'aurora', label: 'Aurora – expressive', gender: 'Female' },
  { id: 'callista', label: 'Callista – professional', gender: 'Female' },
  { id: 'cora', label: 'Cora – caring', gender: 'Female' },
  { id: 'cordelia', label: 'Cordelia – warm', gender: 'Female' },
  { id: 'delia', label: 'Delia – cheerful', gender: 'Female' },
  { id: 'draco', label: 'Draco – trustworthy', gender: 'Male' },
  { id: 'electra', label: 'Electra – knowledgeable', gender: 'Female' },
  { id: 'harmonia', label: 'Harmonia – calm', gender: 'Female' },
  { id: 'helena', label: 'Helena – friendly', gender: 'Female' },
  { id: 'hera', label: 'Hera – professional', gender: 'Female' },
  { id: 'hermes', label: 'Hermes – engaging', gender: 'Male' },
  { id: 'hyperion', label: 'Hyperion – empathetic', gender: 'Male' },
  { id: 'iris', label: 'Iris – cheerful', gender: 'Female' },
  { id: 'janus', label: 'Janus – trustworthy', gender: 'Male' },
  { id: 'juno', label: 'Juno – melodic', gender: 'Female' },
  { id: 'jupiter', label: 'Jupiter – knowledgeable', gender: 'Male' },
  { id: 'luna', label: 'Luna – friendly', gender: 'Female' },
  { id: 'mars', label: 'Mars – smooth', gender: 'Male' },
  { id: 'minerva', label: 'Minerva – friendly', gender: 'Female' },
  { id: 'neptune', label: 'Neptune – polite', gender: 'Male' },
  { id: 'odysseus', label: 'Odysseus – calm', gender: 'Male' },
  { id: 'ophelia', label: 'Ophelia – enthusiastic', gender: 'Female' },
  { id: 'orion', label: 'Orion – calm', gender: 'Male' },
  { id: 'orpheus', label: 'Orpheus – confident', gender: 'Male' },
  { id: 'pandora', label: 'Pandora – melodic', gender: 'Female' },
  { id: 'phoebe', label: 'Phoebe – energetic', gender: 'Female' },
  { id: 'pluto', label: 'Pluto – empathetic', gender: 'Male' },
  { id: 'saturn', label: 'Saturn – confident', gender: 'Male' },
  { id: 'selene', label: 'Selene – energetic', gender: 'Female' },
  { id: 'thalia', label: 'Thalia – enthusiastic', gender: 'Female' },
  { id: 'theia', label: 'Theia – polite', gender: 'Female' },
  { id: 'vesta', label: 'Vesta – patient', gender: 'Female' },
  { id: 'zeus', label: 'Zeus – deep', gender: 'Male' },
];
