name: Vercel Production Deployment

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read
  deployments: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Skip environment variable setting - use Vercel dashboard configuration instead
      # - name: Set environment variables in Vercel
      #   uses: dkershner6/vercel-set-env-action@v3
      #   with:
      #     token: ${{ secrets.VERCEL_TOKEN }}
      #     projectName: dashboard
      #     envVariableKeys: NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: false

      - name: Create deployment status
        uses: actions/github-script@v7
        with:
          script: |
            if (context.payload.deployment?.id) {
              github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: context.payload.deployment.id,
                state: 'success',
                environment_url: 'https://www.spoqen.com',
                description: 'Deployment completed successfully'
              });
            } else {
              console.log('No deployment ID found, skipping status creation');
            }

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify deployment status
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ needs.deploy.result }}';
            const message = status === 'success' 
              ? '✅ Deployment successful!' 
              : '❌ Deployment failed!';

            console.log(`${message} - Status: ${status}`); 