name: Vercel Production Deployment

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read
  deployments: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables in Vercel
        uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: my-v0-project
          envVariableKeys: NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          TARGET_NEXT_PUBLIC_SUPABASE_URL: preview,development,production
          TYPE_NEXT_PUBLIC_SUPABASE_URL: encrypted

          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          TARGET_NEXT_PUBLIC_SUPABASE_ANON_KEY: preview,development,production
          TYPE_NEXT_PUBLIC_SUPABASE_ANON_KEY: encrypted

          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          TARGET_NEXT_PUBLIC_SITE_URL: preview,development,production
          TYPE_NEXT_PUBLIC_SITE_URL: encrypted

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Create deployment status
        uses: actions/github-script@v7
        with:
          script: |
            if (context.payload.deployment?.id) {
              github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: context.payload.deployment.id,
                state: 'success',
                environment_url: 'https://spoqen-dashboard.vercel.app',
                description: 'Deployment completed successfully'
              });
            } else {
              console.log('No deployment ID found, skipping status creation');
            }

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Notify deployment status
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ needs.deploy.result }}';
            const message = status === 'success' 
              ? '✅ Deployment successful!' 
              : '❌ Deployment failed!';

            console.log(`${message} - Status: ${status}`); 